-- Mateus Conaway and Kaylah Tan
-- 05/05/24
-- CS302: Databases 

-- WWV Wineries 
-- Insert statements for the Wines table column 

DROP TABLE IF EXISTS wwvwineries_schema.Operating_Hours;

INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("1", "Monday, Tuesday, Wednesday, Thursday", "10:00:00", "2:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("1", "Friday, Saturday", "10:00:00", "4:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("2", "Monday, Tuesday, Wednesday, Thursday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("2", "Friday, Saturday", "11:00:00", "4:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("3", "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("4", "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday", "11:00:00", "4:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("5", "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("6", "Sunday, Monday, Tuesday, Wednesday, Thursday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("7", "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("8", "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("9", "Monday, Tuesday, Wednesday, Thursday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("10", "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday", "11:00:00", "4:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("11", "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("12", "Sunday, Monday, Tuesday, Wednesday, Thursday, Friday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("12", "Saturday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("13", "Monday, Tuesday, Wednesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("13", "Sunday, Thursday", "11:00:00", "4:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("13", "Friday, Saturday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("14", "Monday, Tuesday, Wednesday, Thursday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("14", "Friday, Saturday", "11:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("14", "Sunday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("15", "Sunday, Monday, Tuesday, Wednesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("15", "Thursday, Friday, Saturday, Sunday", "11:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("16", "Thursday, Friday, Saturday, Sunday, Monday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("16", "Tuesday, Wednesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("17", "Monday, Tuesday, Wednesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("17", "Sunday, Thursday", "1:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("17", "Friday, Saturday", "11:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("18", "Monday, Thursday, Friday, Saturday", "12:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("18", "Tuesday, Wednesday", NULL, "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("18", "Sunday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("19", "Sunday, Monday, Tuesday, Wednesday, Thursday", "11:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("19", "Friday, Saturday", "11:00:00", "6:30:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("20", "Sunday, Monday, Tuesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("20", "Wednesday, Thursday, Friday, Saturday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("21", "Sunday, Monday, Tuesday, Wednesday, Thursday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("21", "Friday", "11:00:00", "7:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("21", "Saturday", "11:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("22", "Sunday, Monday, Tuesday, Wednesday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("22", "Thursday, Friday, Saturday,", "11:00:00", "7:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("23", "Sunday, Monday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("23", "Tuesday, Wednesday, Thursday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("23", "Friday, Saturday", "10:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("24", "Sunday, Monday, Tuesday, Wednesday, Thursday", "1:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("24", "Friday, Saturday", "12:00:00", "7:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("25", "Sunday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("25", "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday", "11:00:00", "8:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("26", "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday", "10:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("27", "Monday, Tuesday, Wednesday, Thursday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("27", "Friday, Saturday", "11:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("27", "Sunday", "11:00:00", "4:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("28", "Sunday, Monday, Tuesday, Wednesday, Thursday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("28", "Friday", "4:00:00", "19");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("28", "Saturday", "11:00:00", "8:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("29", "Monday, Tuesday, Wednesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("29", "Thursday, Friday, Saturday, Sunday", "12:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("30", "Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("31", "Sunday, Monday, Tuesday, Wednesday, Thursday", "11:00:00", "7:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("31", "Friday, Saturday", "11:00:00", "10:30:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("32", "Sunday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("32", "Monday, Tuesday, Wednesday", "11:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("32", "Thursday, Friday, Saturday", "11:00:00", "8:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("33", NULL, NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("34", "Monday, Tuesday, Wednesday, Thursday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("34", "Friday", "3:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("34", "Sunday, Saturday", "12:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("35", "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("36", "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday", "10:00:00", "4:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("36", "Sunday", "11:00:00", "4:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("37", "Tuesday, Wednesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("37", "Sunday, Monday, Thursday, Friday, Saturday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("38", "Monday, Wednesday", "12:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("38", "Tuesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("38", "Thursday", "12:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("38", "Friday, Saturday", "11:00:00", "8:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("38", "Sunday", "11:00:00", "2:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("38", "Monday, Tuesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("39", "Sunday, Monday, Tuesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("39", "Wednesday, Thursday, Friday, Saturday", "11:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("40", "Tuesday, Wednesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("40", "Monday, Thursday, Sunday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("40", "Friday, Saturday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("41", "Sunday, Monday, Tuesday, Wednesday", "12:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("41", "Thursday, Friday, Saturday", "12:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("41", "Monday, Tuesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("42", "Sunday, Wednesday, Thursday", "12:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("42", "Friday, Saturday", "12:00:00", "7:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("42", "Monday, Tuesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("43", "Monday, Tuesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("43", "Sunday, Wednesday, Thursday, Friday, Saturday", "12:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("44", "Monday, Thursday", "12:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("44", "Sunday, Friday", "11:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("44", "Tuesday, Wednesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("44", "Saturday", "12:00:00", "7:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("45", "Tuesday, Wednesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("45", "Sunday, Monday", "12:00:00", "4:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("45", "Thursday", "2:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("45", "Friday, Saturday", "12:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("46", "Monday, Tuesday, Wednesday, Thursday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("46", "Sunday, Friday, Saturday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("47", "Monday, Tuesday, Wednesday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("47", "Thursday, Friday, Saturday", "11:00:00", "8:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("47", "Sunday", "12:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("48", "Monday, Tuesday, Wednesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("48", "Sunday, Thursday, Friday, Saturday", "12:00:00", "7:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("49", "Tuesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("49", "Sunday, Monday, Wednesday, Thursday, Friday, Saturday", "11:00:00", "6:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("50", "Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday", "10:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("51", "Monday, Tuesday, Wednesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("51", "Sunday, Thursday, Friday, Saturday", "12:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("52", "Monday, Tuesday, Sunday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("52", "Wednesday, Thursday, Friday, Saturday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("53", "Sunday, Monday, Tuesday, Wednesday, Thursday, Saturday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("53", "Friday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("54", "Monday, Tuesday", NULL, NULL);
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("54", "Sunday, Wednesday, Thursday, Friday, Saturday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("55", "Sunday, Monday, Thursday, Friday, Saturday", "11:00:00", "5:00:00");
INSERT INTO wwvwineries_schema.Operating_Hours (`Winery_ID`, `Days_Of_Week`, `Open`, `Close`) VALUES ("55", "Tuesday, Wednesday", NULL, NULL);
